name: OpenMapTiles

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: openmaptiles/openmaptiles
          ref: v3.14

      - name: Setup environment
        run: make
