name: OpenMapTiles

on: [push]

env:
  area: us-west
  MAX_ZOOM: 14

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: openmaptiles/openmaptiles
          ref: v3.14

      - name: Setup environment
        run: make

      - name: Start up the database
        run: make start-db

      - name: Import external data
        run: make import-data

      - name: Download data extracts
        run: make download-geofabrik

      - name: Import OSM data
        run: make import-osm

      - name: Import Wikidata
        run: make import-wikidata

      - name: Create and import SQL functions
        run: make import-sql

      - name: Generate bbox file
        run: make generate-bbox-file

      - name: Generate tiles
        run: make generate-tiles-pg

      - name: Stop PostgreSQL service
        run: make stop-db

      - name: Upload the .mbtiles file
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: data/tiles.mbtiles
